[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

lib_deps =
    # Aponta explicitamente para a branch estável 'humble'
    https://github.com/micro-ROS/micro_ros_platformio.git
    jrowberg/I2Cdevlib-MPU6050

build_flags =
    -DMICRO_ROS_TRANSPORT_ARDUINO_SERIAL
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

# Configurações específicas que a biblioteca micro-ROS lê durante o Meta-Build
board_microros_distro = humble
board_microros_transport = serial

board_build.partitions = default.csv